services:
  - type: web
    name: hamikdash-frontend
    env: static
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /terms
        destination: /index.html
      - type: rewrite
        source: /returns
        destination: /index.html
      - type: rewrite
        source: /payment/success
        destination: /index.html
      - type: rewrite
        source: /payment/error
        destination: /index.html
      - type: rewrite
        source: /product/*
        destination: /index.html
      - type: rewrite
        source: /cart
        destination: /index.html
      - type: rewrite
        source: /admin
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
